### ISSUE TITLE
postcss-all-link-colors

### ISSUE THREAD

**Issue by jednano** [steffenmllr/postcss-link-colors#1]
I see that postcss-link-colors is already taken, so I had to name mine [postcss-all-link-colors](https://github.com/jedmao/postcss-all-link-colors). I would have submitted a PR, but it's rather a different way of doing things. What do you think about my plugin?

**Comment by steffenmllr** [comment]
You plugins looks great! It seems like we are doing the same thing here just with a different syntax or?
The module is a port this simple sass snippet:

``` scss
//
// Link colors
//
@mixin link-colors($normal, $hover: false, $active: false, $visited: false, $focus: false) {
  color: $normal;
  @if $visited {
    &:visited {
      color: $visited;
    }
  }
  @if $focus {
    &:focus {
      color: $focus;
    }
  }
  @if $hover {
    &:hover {
      color: $hover;
    }
  }
  @if $hover == false {
    &:hover {
      color: lighten($normal, 12%);
    }
  }
  @if $active {
    &:active {
      color: $active;
    }
  }
}
```
